# TODO def task_system.get_reparse_prompt(failed_task: str,
#                                   error)


